feat: add state property
oclif/core pull request #206
Opened 2021-07-30 20:52 UTC by mdonnalley

Add a `state` property to the `Command` and `Config` classes to support marking commands and/or plugins as beta

2021-07-30 20:59 UTC, peternhale requested changes

2021-07-30 20:59 UTC, peternhale commented on src/help/index.ts
> +    console.log(this.config.pjson?.oclif?.state, plugin?.pjson?.oclif?.state, command.state)
@mdonnalley Please remove if not needed

2021-07-30 21:29 UTC, RodEsp approved these changes
I have a feeling we'll need to change the `This command is in ${state}` verbiage but that'll come after design decisions.

Looks good!

2021-08-02 21:04 UTC, peternhale approved these changes

2021-08-03 17:32 UTC, merged