feat: add integration tests
oclif/core pull request #339
Opened 2022-01-03 22:17 UTC by mdonnalley

Adds integration tests. These tests do the following:
- clone the hello-world repo
- adds well-known plugins to the hello-world CLI
- links the local oclif/core version so that the hello-world CLI and all plugins use that version 
- runs various tests

@W-10328827@

2022-01-04 13:10 UTC, peternhale requested changes

2022-01-04 15:28 UTC, mdonnalley commented on test/integration/plugins.e2e.ts
> +      it('should uninstall the plugin', async () => {
@peternhale no, it shouldn't have any effect since the plugin it's installing and uninstalling isn't used elsewhere in these tests

2022-01-04 16:57 UTC, RodEsp approved these changes

2022-01-04 16:59 UTC, RodEsp approved these changes

2022-01-05 15:03 UTC, peternhale approved these changes

2022-01-05 18:14 UTC, merged