chore: simplify ESM `execute` example
oclif/core pull request #942
Opened 2024-02-08 19:53 UTC by mon-jai

2024-02-08 22:50 UTC, mon-jai commented
Signed

2024-02-12 15:44 UTC, mdonnalley requested changes

2024-02-12 15:44 UTC, mdonnalley commented on src/execute.ts
> + * await oclif.execute({development: true, dir: import.meta.url})
With `import {execute} from '@oclif/core'`, there's no longer an oclif namespace - so it should now be `execute({development: true, dir: import.meta.url})`

2024-02-12 19:55 UTC, mdonnalley approved these changes

2024-02-12 19:56 UTC, mdonnalley commented
Thanks @mon-jai 🏆

2024-02-12 19:56 UTC, merged

2024-02-12 20:10 UTC, mon-jai commented
@mdonnalley Follow-up PR for [the ESM template](https://github.com/oclif/hello-world-esm/pull/129) and [documentations](https://github.com/oclif/oclif.github.io/pull/223).